// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSz0Txo5y9EZENGrxVgwnnhafC2PvQS4',
    appId: '1:47534430350:web:df31fcdc22223d104dd1df',
    messagingSenderId: '47534430350',
    projectId: 'tasbihplus-baf68',
    authDomain: 'tasbihplus-baf68.firebaseapp.com',
    storageBucket: 'tasbihplus-baf68.firebasestorage.app',
    measurementId: 'G-RYGBS9WW43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GcNf89-2YLO8uDf4b9n6HMkhlc89e1w',
    appId: '1:47534430350:android:be4fdd72cb615bee4dd1df',
    messagingSenderId: '47534430350',
    projectId: 'tasbihplus-baf68',
    storageBucket: 'tasbihplus-baf68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YW8sx2rbkPmuhYiO33ZMTeybi5gpGac',
    appId: '1:47534430350:ios:d2441d22ad422dff4dd1df',
    messagingSenderId: '47534430350',
    projectId: 'tasbihplus-baf68',
    storageBucket: 'tasbihplus-baf68.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4YW8sx2rbkPmuhYiO33ZMTeybi5gpGac',
    appId: '1:47534430350:ios:d2441d22ad422dff4dd1df',
    messagingSenderId: '47534430350',
    projectId: 'tasbihplus-baf68',
    storageBucket: 'tasbihplus-baf68.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaSz0Txo5y9EZENGrxVgwnnhafC2PvQS4',
    appId: '1:47534430350:web:af74fee70763d26f4dd1df',
    messagingSenderId: '47534430350',
    projectId: 'tasbihplus-baf68',
    authDomain: 'tasbihplus-baf68.firebaseapp.com',
    storageBucket: 'tasbihplus-baf68.firebasestorage.app',
    measurementId: 'G-W5NY7EQG0J',
  );

}